/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateWarningLetterRouteImport } from './routes/generate.warning-letter'
import { Route as GenerateOfferLetterRouteImport } from './routes/generate.offer-letter'
import { Route as GenerateLeavePolicyRouteImport } from './routes/generate.leave-policy'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateWarningLetterRoute = GenerateWarningLetterRouteImport.update({
  id: '/generate/warning-letter',
  path: '/generate/warning-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateOfferLetterRoute = GenerateOfferLetterRouteImport.update({
  id: '/generate/offer-letter',
  path: '/generate/offer-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateLeavePolicyRoute = GenerateLeavePolicyRouteImport.update({
  id: '/generate/leave-policy',
  path: '/generate/leave-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/generate': typeof ApiGenerateRoute
  '/generate/leave-policy': typeof GenerateLeavePolicyRoute
  '/generate/offer-letter': typeof GenerateOfferLetterRoute
  '/generate/warning-letter': typeof GenerateWarningLetterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/generate': typeof ApiGenerateRoute
  '/generate/leave-policy': typeof GenerateLeavePolicyRoute
  '/generate/offer-letter': typeof GenerateOfferLetterRoute
  '/generate/warning-letter': typeof GenerateWarningLetterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/generate': typeof ApiGenerateRoute
  '/generate/leave-policy': typeof GenerateLeavePolicyRoute
  '/generate/offer-letter': typeof GenerateOfferLetterRoute
  '/generate/warning-letter': typeof GenerateWarningLetterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/generate'
    | '/generate/leave-policy'
    | '/generate/offer-letter'
    | '/generate/warning-letter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/generate'
    | '/generate/leave-policy'
    | '/generate/offer-letter'
    | '/generate/warning-letter'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/generate'
    | '/generate/leave-policy'
    | '/generate/offer-letter'
    | '/generate/warning-letter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  GenerateLeavePolicyRoute: typeof GenerateLeavePolicyRoute
  GenerateOfferLetterRoute: typeof GenerateOfferLetterRoute
  GenerateWarningLetterRoute: typeof GenerateWarningLetterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/warning-letter': {
      id: '/generate/warning-letter'
      path: '/generate/warning-letter'
      fullPath: '/generate/warning-letter'
      preLoaderRoute: typeof GenerateWarningLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/offer-letter': {
      id: '/generate/offer-letter'
      path: '/generate/offer-letter'
      fullPath: '/generate/offer-letter'
      preLoaderRoute: typeof GenerateOfferLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/leave-policy': {
      id: '/generate/leave-policy'
      path: '/generate/leave-policy'
      fullPath: '/generate/leave-policy'
      preLoaderRoute: typeof GenerateLeavePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  GenerateLeavePolicyRoute: GenerateLeavePolicyRoute,
  GenerateOfferLetterRoute: GenerateOfferLetterRoute,
  GenerateWarningLetterRoute: GenerateWarningLetterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
